security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            stateless: true
            logout: ~
            guard:
                authenticators:
                    - App\Security\ApiKeyAuthenticator
    access_control:
        - { path: '^/api', roles: ROLE_API }