parameters:
    allowed_domains:
        - 'example.com'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Validator\Constraints\ContainsAllowedDomainsValidator:
        class: 'App\Validator\Constraints\ContainsAllowedDomainsValidator'
        arguments:
            - '%allowed_domains%'
